### PR TITLE
Feature/intro to docker

### PR DESCRIPTION
**Pull request by puja108**
first version of our hands-on intro to docker, to be integrated after the docs update

### CODE REVIEW

**Comment by puja108** [comment]
RFR @marians @luebken, but has time as we will wait with deployment until docs restructuring is deployed

**Comment by puja108** [comment]
@marians can we publish this? not sure where the linking on the guides page happens

**Comment by marians** [comment]
Some comments:

* The guide will automatically appear on the page http://docs.giantswarm.io/guides/ once it's deployed.
* Linking it on the start page under "More Guides", which I'd recommend, requires an edit in https://github.com/giantswarm/docs/blob/master/swarmdocs/layouts/index.html. Feel free to create a PR there.
* The Markdown file needs front matter. Please check the other guides as a template. See http://gohugo.io/content/front-matter/ for details.
* To have control over the code syntax highlighting, I suggest you always put code blocks in triple backticks instead of indenting them. This allows adding of a syntax indicator. With shell commands, this requires the special indicator `nohighlight` after the opening triple backticks.

**Comment by marians** [comment]
BTW, we use the TOML frontmatter syntax. The `weight` attributes allows to order the pages. The `categories` attribute allows to set the "basic" or "advanced" category.

**Comment by puja108** [comment]
ok, all done, I adjusted the weight so it goes right below hello world but above the firstapp guides

**Comment by marians** [comment]
Great! LGTM.

**Pull request merged**
