### PR TITLE
Added install block on Windows

### PR DESCRIPTION
**Pull request by marians**
@webwurst @luebken @kordless @puja108 - Is anybody of you able to test how logging in to the boot2docker VM works on Windows? Assuming it's the same as on Mac, it should be `boot2docker ssh`, but I'd like confirmation before we publish this.

### CODE REVIEW

**Comment by puja108** [comment]
from what I read it seems like all commands are still there. I currently can't test it, cause my Windows VM is 32 bit. I might be able to check it out on the desktop tomorrow

**Comment by marians** [comment]
Good point regarding 32 bit. We should note that.

**Comment by puja108** [comment]
so, `boot2docker ssh` is right, you just need to start Boot2Docker by clicking the "Boot2Docker Start" Icon. Then `boot2docker ssh`. Then the linux install, however, the `tar`command needs to be run as `sudo tar ...` everything else is fine.

**Comment by puja108** [comment]
swarm_on_windows_1024

**Comment by marians** [comment]
I updated the content and tried to made it much more clear what to do, step by step. Ready for your reviews.

**Comment by puja108** [comment]
fixed some minor wordings, otherwise LGTM now

**Comment by marians** [comment]
Thanks!

**Pull request merged**
