### PR TITLE
Customer support info page

### PR DESCRIPTION
**Pull request by webwurst**
First draft.
Where should we place this?
Does it cover all important aspects?
Right tone?

Let's discuss!

### CODE REVIEW

**Comment by marians** [comment]
I suppose that the purpose of this page is to guide users in a situation where they need our help and guide them to the right channels. Correct?

If the above is correct, I would cut out a lot of stuff that doesn't really help to fulfil that purpose or that. (I see that with the latest commit, some of that has happened already.)

It seems that many hints apply to certain channels only, so probably giving some structure like "general info", then channel-specific info might make sense.

Last but not least: I'd love to see that page as `goantswarm.io/support/`, to make it more clear that this is an integral part of our offering. I would like to link to it from the global footer, so it's only one click away from every page we have.

**Comment by puja108** [comment]
+1 






I suppose that the purpose of this page is to guide users in a situation where they need our help and guide them to the right channels. Correct?


If the above is correct, I would cut out a lot of stuff that doesn't really help to fulfil that purpose or that. (I see that with the latest commit, some of that has happened already.)


It seems that many hints apply to certain channels only, so probably giving some structure like "general info", then channel-specific info might make sense.


Last but not least: I'd love to see that page as goantswarm.io/support/, to make it more clear that this is an integral part of our offering. I would like to link to it from the global footer, so it's only one click away from every page we have.

**Comment by puja108** [comment]
@webwurst do you want to move this to our website repo as a new PR there?

**Comment by marians** [comment]
Closing here

**Pull request closed without merging**
