### PR TITLE
Adding Fundamentals content

### PR DESCRIPTION
**Pull request by marians**
WIP

### CODE REVIEW

**Comment by puja108** [comment]
As talked about in yesterday's planning I think this is ok to merge and then we create an issue to work on architecture and update that.
@teemow do you think that is ok, as you were the one that "didn't like" the current architecture part most.

Alternatively, I would leave out the architecture part (i.e. put it in a different PR) and merge this without it.

**Comment by marians** [comment]
I think without the Architecture part the fundamentals section gets pretty thin.

**Comment by teemow** [comment]
LGTM

**Comment by puja108** [comment]
@marians I seem to have been a bit too early with merging this, could it be that this does not include the nav changes, yet?

**Pull request merged**
