### PR TITLE
Added IP Config for AWS

### PR DESCRIPTION
**Pull request by othylmann**
I learned something, need to create pull request :)

### CODE REVIEW

**Comment by othylmann** [comment]
@puja108 please review. thx.

**Comment by marians** [comment]
Sorry @othylmann, seems like you need to merge with my edits from yesterday. If you can wait, I'll be at the office tomorrow.

**Comment by othylmann** [comment]
I think you need to do that with me tomorrow :)

**Comment by marians** [comment]
@othylmann I resolved the conflict for you. You can merge.

**Pull request merged**
