### PR TITLE
Removing "latest" from examples

### PR DESCRIPTION
**Pull request by marians**
… plus some minor cleanups

### CODE REVIEW

**Comment by marians** [comment]
Related to https://github.com/giantswarm/docs-content/issues/186

RFR @puja108

**Comment by puja108** [comment]
Maybe we should add a note with general advice against `latest` instead of just not mentioning latest tags anymore. And also clearly tell what we recommend instead.

**Comment by marians** [comment]
We actually have such an advice in the text (twice).

**Comment by puja108** [comment]
Sorry, didn't see that, found a missing "to" though through that. LGTM

**Comment by marians** [comment]
Thanks!

**Pull request merged**
