### PR TITLE
added rolling updates

### PR DESCRIPTION
**Pull request by puja108**
mentioned that it automatically does rolling updates and that you get 0 downtime deployment

### CODE REVIEW

**Comment by puja108** [comment]
RFR @kordless @marians @luebken

**Comment by ZeissS** [comment]
we are actually currently not waiting for instances to come back up. We just trigger the start. So for two instances, there still might be a downtime.

**Comment by ZeissS** [comment]
I would not merge this with the current featureset. This was a quickshot and was not really thinked through/designed approrpiately.

**Comment by puja108** [comment]
hmm, good to know @ZeissS, from what @luebken said I thought it was ready to tell our users. We were even thinking of doing a blog post about it...which I already wrote...

**Comment by luebken** [comment]
I just clarified with @ZeissS:

Rolling updates _is deployed_ and working. The current implementation is as follows:
It updates one component: Meaning: Stops it. Deletes it. Loads the new version and starts it.

Note: Once it is in starting it immediately continuous with next instance and it doesnt wait for to startup! Especially if you have two components this can end up with a backend not reachable.

Why?: As @ZeissS wrote it is a first 'prototype' to play and learn with. As user feedback roles in we can improve on it. 

@puja108 so from my point of view: No reason to hold back the docs and the blogpost. But maybe change the wording.

**Comment by puja108** [comment]
Ok, understood, will update wording

**Comment by puja108** [comment]
can someone look at the wording again? @luebken ?

**Comment by ZeissS** [comment]
LGTM

**Pull request merged**
