### PR TITLE
Correct some words

### PR DESCRIPTION
**Pull request by oponder**
Specifities isn't a word. It's either specificities or specifics.

### CODE REVIEW

**Comment by puja108** [comment]
I think this should be `specificities` as `specifics` is also not a common word `specific` is.

**Comment by oponder** [comment]
Specifics is a bit more common than specificities in my experience. Can switch, but I'm ok with either. let me know and i'll edit the PR

**Comment by tommyhobin** [comment]
I've got a strong vote for "specifics"

**Comment by rossf7** [comment]
I also prefer "specifics". I've never used "specificities".

**Comment by marians** [comment]
@oponder Seems like you can merge this

**Pull request merged**
