### PR TITLE
Same command was listed twice.

### PR DESCRIPTION
**Pull request by teklifeinfo**

### CODE REVIEW

**Comment by ZeissS** [comment]
Hey teklifeinfo,

thanks for the PR, but currently `swarm logs` doesn't yet support the app/service/component notation. We are working on this though. 

The duplicate notation comes from explaining the short and long notation of the argument.

**Comment by ZeissS** [comment]
Err, the duplication is just wrong. There is no argument in that part ^^

**Comment by teklifeinfo** [comment]
Should I close this pull request and resubmit?

**Comment by ZeissS** [comment]
Nope, thats awesome. Thank you very much for contributing.

**Comment by marians** [comment]
Thanks!

**Pull request merged**
