### PR TITLE
Rails Guide transform to v2 service definition

### PR DESCRIPTION
**Pull request by webwurst**

### CODE REVIEW

**Comment by webwurst** [comment]
When testing the converted `swarm.json` I get the following error:
```bash
2015-08-04 15:40:32.337 +0000 UTC    - docker  - Status: Image is up to date for mysql:latest
2015-08-04 15:40:32.337 +0000 UTC    - docker  - Digest: sha256:3e633be4546d5549c35f9731280e7c7ef0a272c23dfbe241e08a655920c2ffa1
2015-08-04 15:40:33.885 +0000 UTC    - docker  - error: database is uninitialized and MYSQL_ROOT_PASSWORD not set
2015-08-04 15:40:33.886 +0000 UTC    - docker  - Did you forget to add -e MYSQL_ROOT_PASSWORD=... ?
```

Looks to me that the `env` part does not work as expected. Have to investigate on that further..

**Comment by marians** [comment]
Any update on this? Do env vars now work in the key-value-pair (object) notation?

**Comment by marians** [comment]
BTW, the title still has WIP in it, but the label is "review".

**Comment by webwurst** [comment]
The `swarm.json` works now.

**Comment by marians** [comment]
Merging this into `servicedef-v2`. Further review comments in https://github.com/giantswarm/docs-content/pull/143 please.

**Comment by marians** [comment]
Accidentally merged into master. Reverted. Cherry-picked the two commits.

**Pull request merged**
