### PR TITLE
finalized java guide 

### PR DESCRIPTION
**Pull request by puja108**
only the PNG is still missing

### CODE REVIEW

**Comment by puja108** [comment]
@marians could you please check and also create the PNG?

**Comment by marians** [comment]
Should have noticed when reviewing the code, but now I actually ran it.

In the Makefile, shouldn't we make redis run in the background? That would mean an additional -d, but no `--rm` in `docker run -p 6379:6379 -d --name redis redis`.

Also, something isn't right with the temperature calculation:

    Live weather: The current temperature is 281.976 farenheit and the wind is 2.22 mph.

Do we really want Fahrenheit? Even if yes, the number can't be right. Actually, OpenWeatherMap returns Kelvin. And what about mph vs. km/h?

**Comment by marians** [comment]
Another thing on the code: Currently I don't see log output when the API is queried. This would be good to have, since otherwise it's hard to demonstrate the use of the Redis cache.

**Comment by marians** [comment]
Regarding the PNG, you find the Google Drawing here: https://docs.google.com/a/giantswarm.io/drawings/d/1u_mirVzvq5_Un9MahlCAXO0G8Uwi8AASxRzqIjsoYUA/edit

Use the File > Download as > PGN image function to save a local copy.

**Comment by puja108** [comment]
fixed issues in https://github.com/giantswarm/giantswarm-firstapp-java/pull/2 and added the changes to the docs

**Comment by marians** [comment]
I think you could merge then. :)

**Comment by marians** [comment]
Now available at http://docs.giantswarm.io/guides/your-first-application/java/

**Pull request merged**
