### PR TITLE
updates to scaling

### PR DESCRIPTION
**Pull request by puja108**
Added disclaimer for volumes, link to scaling policy in swarm.json and link to pods (as you can scale pods)

Also added the text from pods about scaling components in a pod, with link

### CODE REVIEW

**Comment by puja108** [comment]
This is regarding https://github.com/giantswarm/docs-content/issues/98 but covers a bit more. after review I will do the same with scaledown.md

**Comment by puja108** [comment]
RFR @marians @ewoutp

**Comment by marians** [comment]
The volumes info also applies to "scaledown", so we should also add something along the lines there.

**Comment by puja108** [comment]
@marians as mentioned in the comment above, I wanted to first let you gus review scaleup so that I can then apply the reviewed changes to scaledown ;)

**Comment by marians** [comment]
Sorry, missed that :p

**Comment by marians** [comment]
lgtm

**Pull request merged**
