### PR TITLE
fixed docker compose guide

### PR DESCRIPTION
**Pull request by puja108**
docker-compose.yml has to be changed manually as it does not support
environment variables

### CODE REVIEW

**Comment by puja108** [comment]
workaround for https://github.com/giantswarm/giantswarm-firstapp-java/issues/6

RFR @luebken

**Comment by marians** [comment]
@luebken If you can review this, we might deploy it today.

**Comment by luebken** [comment]
LGTM

**Comment by marians** [comment]
Merging this to publish tonight.

**Pull request merged**
