### PR TITLE
Login reference page

### PR DESCRIPTION
**Pull request by marians**
New content for the reference page

Happy for a review by either @puja108 @kordless @luebken

### CODE REVIEW

**Comment by puja108** [comment]
made some minor corrections, LGTM.

**Comment by marians** [comment]
Thanks @puja!

**Comment by luebken** [comment]
As always very thought through documentation by Marian. 




LGTM



-- 

Giant Swarm GmbH · c/o Startplatz · Mediapark 5 · D-50670 Köln

Mobile: +49 176 21236361 · @luebken · giantswarm.io

Handelsregister: Amtsgericht Köln, HRB 81484· Sitz der Gesellschaft: Köln

Geschäftsführer: Timo Derstappen, Henning Lange, Oliver Thylmann

**Comment by marians** [comment]
Available at docs.giantswarm.io/reference/login/

**Pull request merged**
