### PR TITLE
Polish YAML block definitions

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards #288 
Unify YAML block definition and try to solve not render YAML blocks

### CODE REVIEW

**Comment by rossf7** [comment]
@pipo02mix I noticed this too. I think as well as making the yaml blocks lower case they are indented. Removing the whitespace should fix the formatting.

**Comment by pipo02mix** [comment]
@rossf7 but if I remove the indent from the code blocks then the paragraph just below them are converted to block codes too or they cannot be indented as bullet paragraphs. So how can I solve it?

**Comment by rossf7** [comment]
Sorry looks like I was wrong and the code blocks should be indented.

The docs use the Hugo site generator and there is an open issue. The workaround mentioned [here](https://github.com/gohugoio/hugo/issues/2928) with a newline after the code block might work?

**Comment by pipo02mix** [comment]
I did it but I think the problem is not on the order list but the paragraph between code blocks. I have tried different ways but they are still being displayed as code blocks. any idea?

**Comment by rossf7** [comment]
@pipo02mix Sorry I'm not sure either. Maybe try posting in #sig-content? As someone else might have hit this.

**Comment by pipo02mix** [comment]
I have followed @marians [advise](https://gigantic.slack.com/archives/C02NGJTJN/p1515497844000259?thread_ts=1515489168.000017&cid=C02NGJTJN) and now it looks better. Not sure if there are more docs pages will need refactor too

**Pull request merged**
