### PR TITLE
Add documentation about entrypoint.

### PR DESCRIPTION
**Pull request by ZeissS**
see https://github.com/giantswarm/user-config/pull/13 and https://github.com/giantswarm/app-service/pull/182

### CODE REVIEW

**Comment by ZeissS** [comment]
ping @marians 

This is not available in the CLI yes. See https://github.com/giantswarm/cli/wiki#0160-to-current

**Comment by marians** [comment]
+10 for providing a docs PR! :)

Docker's `ENTRYPOINT` expects either an array ("exec form") or a string ("shell form"). We seem to only accept a key value. Does this mean we only support the shell form? What if I give a value contianing spaces, like `"/some/path --some-args"`.

**Comment by ZeissS** [comment]
This is actually the same as doing `docker run --entrypoint=$ENTRYPOINT $IMAGE`. You can only pass one value there as well.

**Comment by marians** [comment]
@ZeissS Can you simply add a phrase like "Expects one string, optionally containing white space"?

**Comment by ZeissS** [comment]
There are no whitespaces allowed. And that its one string is obvious from the fact that it is ONE string? :confused:

**Comment by marians** [comment]
Wasn't obvious to me, at least.

**Comment by marians** [comment]
@ZeissS Let's merge this, so we have it in. We'll clarify whether or not whitespace is allowed in the path at some point.

**Pull request merged**
